### ISSUE TITLE
Build issue after updating to 8.0.0 with bignumber typing

### ISSUE THREAD

**Issue by QuackenbushDev** [ExploreConsulting/netsuite-fasttrack-toolkit-ss2#90]
I'm upgrading our project from 7.3.1 to 8.0.0. When building Typescript is erroring on the bignumber type definition that is bundled with the new release.

I'm using the following versions
tsc: v5.7.3
node: v22.12.0

Here is the included bignumber.d.ts 
```typescript
/// <reference path="./types.d.ts" />

export = BigNumber;

export as namespace BigNumber;
```

Project build output
```
node ➜ /workspaces/Netsuite-Account-Customization $ npm run build

> acount-project@1.0.0 build
> tsc -b && rm src/FileCabinet/tsconfig.tsbuildinfo
src/TypeScript/NFT-SS2-8.0.0/bignumber.d.ts:1:22 - error TS6053: File '/workspaces/Netsuite-Account-Customization/src/TypeScript/NFT-SS2-8.0.0/types.d.ts' not found.
1 /// <reference path="./types.d.ts" />
                       ~~~~~~~~~~~~
src/TypeScript/NFT-SS2-8.0.0/bignumber.d.ts:3:10 - error TS2686: 'BigNumber' refers to a UMD global, but the current file is a module. Consider adding an import instead.
3 export = BigNumber;
           ~~~~~~~~~
src/TypeScript/NFT-SS2-8.0.0/bignumber.d.ts:5:1 - error TS2303: Circular definition of import alias 'BigNumber'.
5 export as namespace BigNumber;
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 3 errors.
```

**Comment by ShawnTalbert** [comment]
Looks like BigNumber changed the types layout in v9 and we'll need to add that new `types.d.ts` to the dist.

I couldn't think of an easy way to test this in NFT itself to protect similar changes in the future. Any thoughts on that welcomed! 

Otherwise I think we can add that extra declarations file and roll 8.0.1? 

Thanks @QuackenbushDev for the rapid report!

**Comment by QuackenbushDev** [comment]
Firstly thank you for this project. Working with NS has been more pleasant since finding this project.

Just thinking out loud here. A simple way to guard against this in the future would be to compile the tests against the gulp output. Should be simple enough to copy the tests folder to the gulp versionedDistPath, run tsc, check if there if errors appear in the output, and then delete the tests/out folder before zipping it up.

Short term I'd second just including the `types.d.ts` file in the output. Long term I'd recommend putting it in a subfolder, and doing a sed on the `bignumber.d.ts` to update the path. Since it's a generic filename I could see other projects possibly conflicting with it.
